### ISSUE TITLE
Compatibility update with newer librosa version in collab

### ISSUE THREAD

**Issue by Gero39** [CorentinJ/Real-Time-Voice-Cloning#645]
Hi, recently the program stopped working in collab due to librosa 0.8.0 update, giving error "module 'librosa' has no attribute 'output'", please solve this problem

**Comment by blue-fish** [comment]
The code changes needed for librosa 0.8.0 are in #572.
However, the collab notebook is not officially maintained or supported, so you will need to make the updates yourself. Please submit a pull request if you get it working.

**Comment by Gero39** [comment]
![image](https://user-images.githubusercontent.com/75932124/106463086-fce34180-64a7-11eb-9c96-948cd6c7746e.png)
I copied all the code from there and this error came up:

> The code changes needed for librosa 0.8.0 are in #572.
> However, the collab notebook is not officially maintained or supported, so you will need to make the updates yourself. Please submit a pull request if you get it working.

**Comment by blue-fish** [comment]
Someone else is going to need to help with the collab notebook if you're going that route.

It's not easy, but you will probably have a better experience running this code from a normal Python environment. It doesn't require a GPU so most hardware is supported. Here are setup instructions for [Windows](https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542), [macOS](https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-766312100), and [Linux](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/615#issuecomment-740270185).

**Comment by blue-fish** [comment]
Closing this issue. Colab notebook is no longer part of this repo. See #656 and #657
